version: '3.8'

services:
  backend-authentication:
    build: ./backend
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 main:app
    networks:
      - web
    expose:
      - 8000
    environment:
      - SECRET_KEY=dev
    restart: unless-stopped
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - backend-authentication
    environment:
      - VIRTUAL_HOST=auth.byleo.net
      - LETSENCRYPT_HOST=auth.byleo.net
      - VIRTUAL_PORT=80
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
