version: '3.8'

services:
  backend-account:
    build: ./backend
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 main:app
    volumes:
      - ./backend/data.db:/app/data.db
    networks:
      - web
    expose:
      - 8000
    environment:
      - SECRET_KEY=dev
    restart: unless-stopped
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 1337:80
    depends_on:
      - backend-account
    environment:
      - VIRTUAL_HOST=account.byleo.net
      - LETSENCRYPT_HOST=account.byleo.net
      - VIRTUAL_PORT=80
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
